- name: Deploy Postgres on dev-workstation
  hosts: dev-workstation
#  vars_files:
#    - secrets.yml
  gather_facts: true
  sudo: true
  user: vagrant
  roles:
    - user
    - package
    - desktop
    - jdk
    - eclipse
    - maven
    - git
    - smartgit
    - workbench

  

